### ISSUE TITLE
APK download link does nothing

### ISSUE THREAD

**Issue by kentonv** [jparyani/Tiny-Tiny-RSS#10]
The endpoint seems to return an empty document. No errors logged anywhere.

**Comment by ocdtrekkie** [comment]
Was this the thing where I noticed that the APK wasn't included after the vagrant-spk changeover was done?

**Comment by ocdtrekkie** [comment]
...Why did I not file an issue for that?

**Comment by ocdtrekkie** [comment]
Oh, because it's issue #9, where I also offered an interim Davros share with the APK file.

**Comment by jparyani** [comment]
Fixed by #11.
