### ISSUE TITLE
feeds do not update at all (not even trying like the last bug)

### ISSUE THREAD

**Issue by voidplayer** [jparyani/Tiny-Tiny-RSS#15]
this seems a different bug 

I leave my sandstorm ttrss open in a tab 24x7. It hasnt updated once in the last 32h at least (looking at the dates of the feeds)

In the logs I can only see this lines:
`
   ** SANDSTORM SUPERVISOR: Grain still in use; staying up for now.`

Closing the tab and reopening is not helping. Clicking on the feeds is doing nothing. closing the grain and reopening do nothing.

Next thing i will try is to reboot the machine. Is there something you want me to check before that?

I also have liferea open 24/7 accessing it.

**Comment by jparyani** [comment]
The code at https://github.com/jparyani/Tiny-Tiny-RSS/blob/93a37aaf0807cede17192ad3cf8f5f2000916f56/.sandstorm/launcher.sh#L40 should be launching the update in a loop.

Also can you try restarting the grain from the topbar (it's the icon between the download button and the key).

**Comment by voidplayer** [comment]
thanks, i finally restarted server so i cant check any further. I will do next time
