### ISSUE TITLE
All feeds have all of a sudden stopped updating

### ISSUE THREAD

**Issue by timshannon** [jparyani/Tiny-Tiny-RSS#20]
Not sure what changed, but none of my feeds are updating anymore, and I know there are new entries.

Probably related; when I try to subscribe to any new feed I get `Couldn't download the specified URL: false`

Things I've tried:
* Starting a brand new grain - Still won't let me add new feeds, and won't update the default tiny tiny rss feeds that a new seed starts with.  Also shows nothing in the Preferences -> System -> Error log page.
* Incognito Mode
* New Browser - Currently on Chrome, tried Firefox.

Not sure what else to try at this point. Seems to be an issue with the server running sandstorm, but I can wget any feeds with no issues from directly on the server.

**Comment by ocdtrekkie** [comment]
This is a bug with hack-session.js on 0.219/0.220 of Sandstorm. This is the reference issue for it: https://github.com/sandstorm-io/sandstorm/issues/3010

**Comment by kentonv** [comment]
Yep, sorry, this was a Sandstorm bug. It's now fixed on Oasis and an update for self-hosters will be posted in about 15 minutes. You'll get the update automatically within 24 hours, or you can type `sudo sandstorm update` to get it immediately (well, after I've posted it in 15 minutes).

**Comment by timshannon** [comment]
Yep, I'm up and running now.

Thanks!
