### ISSUE TITLE
Startup failed

### ISSUE THREAD

**Issue by ocdtrekkie** [jparyani/Tiny-Tiny-RSS#6]
App update has broken my TTRSS!

![tinyrssfail](https://cloud.githubusercontent.com/assets/4399499/9571349/df962d56-4f61-11e5-9332-767c9eaa9a0c.png)

**Comment by jparyani** [comment]
Thanks for reporting this. A new spk has been published, but if you want it early, it's available at http://sandstorm.io/apps/jparyani/tinytinyrss-5.spk

**Comment by ocdtrekkie** [comment]
You're a hero, @jparyani
