### ISSUE TITLE
Cannot resolve host

### ISSUE THREAD

**Issue by ocdtrekkie** [jparyani/Tiny-Tiny-RSS#7]
Is there any reason the ability for TTRSS to connect out may have been broken in the last release? I get "cannot resolve host" errors for all of my feeds.

**Comment by jparyani** [comment]
Oh dang, there were breaking changes in sandstorm-http-bridge that it doesn't handle. Fixing now.

**Comment by jparyani** [comment]
Fixed in c99bc3e373f6057a8f0ba7ebf11b0eb5c2d4b601. It turned out to be a lot of little issues that were a symptom of changing to using vagrant-spk. New version is up on the app market now.
